name: Project Build

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ master ]

jobs:
  docker-build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t test .;
